run-conf/run-configure.sh: Don't invoke fortran build, because we want a pure C build system. -            --enable-autodetect-f77-ldflags \ -            --enable-autodetect-f77-name-mangling \ +            --disable-autodetect-f77-ldflags \ +            --disable-autodetect-f77-name-mangling \ Enable blas interface in libFlame, so blas api layer exists in libflame. libflame can support BLAS itself and no external libblas.a is necessary. -            --disable-builtin-blas \ +            --enable-builtin-blas \ No external link to lapack, because we don't want external liblapack.a. We only need libflame.a functions. --disable-lapack2flame \ --disable-external-lapack-for-subproblems \ -            --enable-external-lapack-interfaces \ +            --disable-external-lapack-interfaces \ no front end currently --disable-blas3-front-end-cntl-trees \ Where to find the built lib and headers: export FLAME_INSTALL_PREFIX= build/config/lib_list: -flablas : don't build this folder to fix "lsame.c" duplicate issue! this is lapack f2c related. build/config/ignore_list +flablas : ignore this folder to fix undefined reference to `zaxpy_', which are many F77 blas functions.
test/Makefile:
+LDFLAGS        := -lm -lpthread=> math and pthread
+HOME := /home2/thomas/libFLAME/libflame.git
+INSTALL_PREFIX := $(HOME)/flame => where is the installed lib and headers

No external blas and lapack
+#LIBBLAS        := $(LIBBLAS_PATH)/libgoto.a
-LIBLAPACK      := $(LIBLAPACK_PATH)/liblapack.a

$run-conf/run-configure.sh
$make -j8
$make install
$cd test
$make test